### ISSUE TITLE
Could functionality for PowerPoint files be added ?

### ISSUE THREAD

**Issue by JoHoGH** [jftuga/spo_view_it#1]

**Comment by jftuga** [comment]
The current code only really does one thing:

* change the URL parameter from: `action=default` to `DefaultItemOpen=1&Action=View`

Since it has no specific knowledge of `docx`, `xlsx` or `pptx`, I am not sure how I could include forcing it for PowerPoint files.

**Comment by JoHoGH** [comment]
Thanks. I should have asked if this was expected to work for `pptx` or not. Watching the screen a bit more closely, the file does actually open with "Viewing" only, so the link does work, But then almost instantly the document switches to "Editing" , so my problem lies elsewhere.
